#!/usr/bin/env python
"""Build the workshop's trilingual content bundle from the hand-edited YAML.

    python scripts/build_workshop_content.py            # build (and validate)
    python scripts/build_workshop_content.py --check    # validate only

Reads
    website/workshop/content/ui.yaml            interface strings
    website/workshop/content/<topic>.yaml       one file per workshop topic
    website/data/levers_<sector>.js             AUTO-GENERATED by the notebooks
    website/data/history_<sector>.js            AUTO-GENERATED by the notebooks

Writes
    website/data/workshop_content.js            window.NW_WS_CONTENT

The split is deliberate: prose lives in the YAML, numbers come from the
notebooks. Any figure quoted in the prose is written as a {placeholder} and
resolved here from the lever's `facts` block, so a number in the workshop text
can never drift from the model. See docs/workshop_module.md.

The build fails — rather than warns — on any of:
  * a string missing one of the declared languages;
  * a fact without a `kind` or a `source`, or with an unknown `kind`;
  * a {placeholder} that does not resolve;
  * lever ids that disagree between the YAML and the notebook export;
  * a lever whose history series can be neither resolved nor explicitly
    declared absent with a reason.
"""
import argparse
import datetime as dt
import glob
import json
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT_DIR = os.path.join(ROOT, "website", "workshop", "content")
DATA_DIR = os.path.join(ROOT, "website", "data")
OUT = os.path.join(DATA_DIR, "workshop_content.js")

FACT_KINDS = {"trend", "structure", "benchmark", "tangible", "caution"}
# Placeholders the *page* fills in at run time, so the build must leave them alone.
RUNTIME_PLACEHOLDERS = {"value", "valuePerDay", "valuePerYear",
                        "n", "total", "twh", "delta", "year", "done"}
NO_GROUPING = {"refYear", "targetYear"}
# {key}, {key:abs} (drop the sign), {key:d2} (force two decimals)
PLACEHOLDER_RE = re.compile(r"\{([A-Za-z][A-Za-z0-9_]*)(?::(abs|d[0-4]))?\}")
NBSP = "\u00a0"

TRANSLATABLE_FIELDS = ("question", "short", "subtitle", "tangible", "justification",
                       "debate", "historyNote")

# Shown before the group commits to a value. These must never quote negaWatt's own
# choice, or the exercise hands over its answer. `justification`, `debate` and any
# fact flagged `reveal: true` are exempt — they are the reveal.
PRE_ANSWER_FIELDS = ("question", "short", "subtitle", "tangible")


class BuildError(Exception):
    pass


def load_generated(name):
    path = os.path.join(DATA_DIR, name)
    if not os.path.isfile(path):
        raise BuildError(f"{name} is missing — run the notebook export cell first")
    txt = open(path, encoding="utf-8").read()
    match = re.search(r"= (\{.*\});\n\Z", txt, re.S)
    if not match:
        raise BuildError(f"{name} does not look like a generated window.* file")
    return json.loads(match.group(1))


def natural_decimals(value, cap=4):
    """How many decimals the value actually carries, so nothing gets padded.

    Every exported figure is already rounded in the notebook, so -6.7 must render
    as "-6.7" and never as "-6.70".
    """
    text = repr(float(value))
    if "e" in text or "E" in text:
        return cap
    frac = text.split(".")[1] if "." in text else ""
    return min(len(frac.rstrip("0")), cap)


def format_number(value, lang, decimals=None, group=True):
    """Render a number the way the target language writes it.

    French and Dutch take a decimal comma and a no-break space for thousands;
    English a decimal point and a comma. The sign is the typographic minus
    (U+2212), not a hyphen.
    """
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return str(value)
    if decimals is None:
        decimals = natural_decimals(value)
    text = f"{abs(value):,.{decimals}f}"
    if not group or abs(value) < 1000:
        text = text.replace(",", "")
    elif lang == "fr":
        text = text.replace(",", NBSP)          # French: no-break space
    elif lang == "nl":
        text = text.replace(",", "\u0000")       # Dutch: a point, via a placeholder
    if lang in ("fr", "nl"):
        text = text.replace(".", ",")           # decimal comma
    text = text.replace("\u0000", ".")           # ...then the Dutch thousands point
    return ("\u2212" if value < 0 else "") + text


def resolve(text, values, lang, where, errors, decimals_by_key=None):
    """Substitute {placeholder}s, leaving the run-time ones in place."""
    decimals_by_key = decimals_by_key or {}

    def sub(match):
        key, modifier = match.group(1), match.group(2)
        if key in RUNTIME_PLACEHOLDERS:
            return match.group(0)
        if key not in values:
            errors.append(f"{where}: unknown placeholder {{{key}}} "
                          f"(available: {', '.join(sorted(values)) or 'none'})")
            return match.group(0)
        value = values[key]
        decimals = decimals_by_key.get(key)
        if modifier == "abs" and isinstance(value, (int, float)):
            value = abs(value)
        elif modifier and modifier.startswith("d"):
            decimals = int(modifier[1:])
        return format_number(value, lang, decimals=decimals,
                             group=key not in NO_GROUPING)
    return PLACEHOLDER_RE.sub(sub, text)



def spoiler_check(raw, resolved, lang, where, lever, errors):
    """Refuse text that gives away the negaWatt value before the group answers.

    Two ways it can leak, so both are checked as hard errors:
      * the *raw* YAML quotes one of the lever's `spoilers` fact keys — the
        reduction the scenario assumes, where it sends the shifted kilometres,
        the demand it lands on;
      * the *resolved* text simply prints the target number.
    """
    for match in PLACEHOLDER_RE.finditer(raw or ""):
        name = match.group(1)
        if name == "targetValue" or name in (lever.get("spoilers") or []):
            errors.append(f"{where}: {{{name}}} states negaWatt's own choice and cannot "
                          f"appear before the group answers — move this to the "
                          f"justification, or flag the fact with 'reveal: true'")
    # A pre-answer card must not talk about what negaWatt or "the scenario"
    # assumes at all: saying "this means doubling rail use" leaks the answer just
    # as effectively as printing the number. Sources are metadata, not claims, and
    # are checked separately.
    lowered = (resolved or "").lower()
    for word in ("negawatt", "négawatt", "le scénario", "du scénario", "ce scénario",
                 "het scenario", "the scenario", "dit scenario"):
        if word in lowered:
            errors.append(f"{where}: mentions {word!r}, so it describes negaWatt's own "
                          f"choice — move it to the justification, or flag the fact with "
                          f"'reveal: true'")
            break

    # Check the target at its own precision and one decimal coarser, so "2,0"
    # is caught as well as "2,00". Not the bare integer when the lever has
    # decimals — "2" alone appears in far too much innocent prose.
    decimals = lever.get("decimals", 1)
    renderings = {format_number(lever["targetValue"], lang, decimals=d)
                  for d in {decimals, max(decimals - 1, 1 if decimals else 0)}}
    for shown in renderings:
        pattern = r"(?:^|[^0-9,.\u00a0])" + re.escape(shown) + r"(?:[^0-9,.\u00a0]|$)"
        if re.search(pattern, resolved or ""):
            errors.append(f"{where}: prints the negaWatt value {shown!r} as a standalone "
                          f"number before the group answers — reword it, or flag the fact "
                          f"with 'reveal: true'")
            break


def fold(text):
    """Collapse the line breaks of a YAML block into one line.

    Deliberately not `" ".join(text.split())`: Python treats U+00A0 as
    whitespace, so that would silently destroy the no-break spaces French
    typography needs before "?" and "!" — and then a line could break there,
    orphaning the punctuation.
    """
    return re.sub(r"[ \t\r\n\f\v]+", " ", str(text)).strip()


def raw_text(node, lang):
    """The YAML string for one language, folded, before resolution."""
    if not isinstance(node, dict):
        return ""
    value = node.get(lang)
    return fold(value) if value else ""


def check_multilang(node, languages, where, errors, values=None, decimals_by_key=None):
    """Validate a {fr:…, nl:…, en:…} block and return it with placeholders resolved."""
    if not isinstance(node, dict):
        errors.append(f"{where}: expected one string per language, got {type(node).__name__}")
        return {}
    out = {}
    for lang in languages:
        raw = node.get(lang)
        if raw is None or not str(raw).strip():
            errors.append(f"{where}: missing or empty '{lang}'")
            continue
        text = fold(raw)                           # keeps no-break spaces intact
        out[lang] = (resolve(text, values, lang, f"{where}.{lang}", errors,
                             decimals_by_key) if values else text)
    extra = set(node) - set(languages)
    if extra:
        errors.append(f"{where}: unexpected language key(s) {sorted(extra)}")
    return out


def build(check_only=False):
    errors, warnings = [], []

    # ---------------------------------------------------------------- ui.yaml
    ui_path = os.path.join(CONTENT_DIR, "ui.yaml")
    if not os.path.isfile(ui_path):
        raise BuildError(f"{ui_path} is missing")
    ui_doc = yaml.safe_load(open(ui_path, encoding="utf-8"))
    languages = list(ui_doc["meta"]["languages"])
    default_lang = ui_doc["meta"]["default"]
    if default_lang not in languages:
        errors.append(f"ui.yaml: default language {default_lang!r} is not in {languages}")

    ui_strings = {}
    for key, node in (ui_doc.get("strings") or {}).items():
        ui_strings[key] = check_multilang(node, languages, f"ui.{key}", errors)

    # ------------------------------------------------------------- topic files
    topics = {}
    topic_files = sorted(glob.glob(os.path.join(CONTENT_DIR, "*.yaml")))
    topic_files = [p for p in topic_files if os.path.basename(p) != "ui.yaml"]
    if not topic_files:
        errors.append("no topic YAML found in website/workshop/content/")

    for path in topic_files:
        name = os.path.basename(path)
        doc = yaml.safe_load(open(path, encoding="utf-8"))
        topic_id = doc.get("topic")
        sector = doc.get("sector")
        if not topic_id or not sector:
            errors.append(f"{name}: both 'topic' and 'sector' are required")
            continue

        levers_doc = load_generated(f"levers_{sector}.js")
        history_doc = load_generated(f"history_{sector}.js")
        exported = {lid: lv for lid, lv in levers_doc["levers"].items()
                    if lv.get("topic") == topic_id and lv.get("shown")}

        yaml_levers = doc.get("levers") or {}
        only_yaml = set(yaml_levers) - set(exported)
        only_export = set(exported) - set(yaml_levers)
        if only_yaml:
            errors.append(f"{name}: lever(s) {sorted(only_yaml)} are not exported as "
                          f"shown levers of topic '{topic_id}' by the notebook")
        if only_export:
            errors.append(f"{name}: the notebook exports shown lever(s) "
                          f"{sorted(only_export)} with no content here")

        topic = {
            "sector": sector,
            "title": check_multilang(doc.get("title"), languages, f"{name}.title", errors),
            "lead": check_multilang(doc.get("lead"), languages, f"{name}.lead", errors),
            "intro": check_multilang(doc.get("intro"), languages, f"{name}.intro", errors),
            "order": [lid for lid in yaml_levers if lid in exported],
            "levers": {},
        }

        for lid, content in yaml_levers.items():
            lv = exported.get(lid)
            if lv is None:
                continue
            where = f"{name}.{lid}"
            values = dict(lv.get("facts") or {})
            values.update({
                "refValue": lv["refValue"], "targetValue": lv["targetValue"],
                "refYear": lv["refYear"], "targetYear": lv["targetYear"],
                "unit": lv["unit"],
            })
            # The lever's own values keep the precision the lever declares, so
            # 2.0 persons/car reads "2,00" rather than "2".
            decimals = lv.get("decimals", 1)
            decimals_by_key = {"refValue": decimals, "targetValue": decimals}

            rec = {}
            for field in TRANSLATABLE_FIELDS:
                if field in content:
                    rec[field] = check_multilang(content[field], languages,
                                                 f"{where}.{field}", errors, values,
                                                 decimals_by_key)
                    if field in PRE_ANSWER_FIELDS:
                        for lang, text in rec[field].items():
                            spoiler_check(raw_text(content[field], lang), text, lang,
                                          f"{where}.{field}.{lang}", lv, errors)
            for field in ("question", "short", "justification"):
                if field not in rec:
                    errors.append(f"{where}: '{field}' is required")

            facts = content.get("facts") or []
            pre_answer = [f for f in facts if not f.get("reveal")]
            if len(pre_answer) < 3:
                warnings.append(f"{where}: only {len(pre_answer)} fact(s) shown before the "
                                f"group answers; four work best on the printed card")
            rec["facts"] = []
            for i, fact in enumerate(facts):
                fwhere = f"{where}.facts[{i}]"
                kind = fact.get("kind")
                if kind not in FACT_KINDS:
                    errors.append(f"{fwhere}: kind {kind!r} is not one of {sorted(FACT_KINDS)}")
                if not fact.get("source"):
                    errors.append(f"{fwhere}: every fact needs a 'source'")
                url = fact.get("url")
                if url and not str(url).startswith(("http://", "https://")):
                    errors.append(f"{fwhere}: url {url!r} does not look like a URL")
                entry = {"kind": kind,
                         "text": check_multilang(fact.get("text"), languages,
                                                 f"{fwhere}.text", errors, values,
                                                 decimals_by_key),
                         "source": fact.get("source")}
                if url:
                    entry["url"] = url
                if fact.get("reveal"):
                    entry["reveal"] = True      # held back until the reveal screen
                else:
                    for lang, text in entry["text"].items():
                        spoiler_check(raw_text(fact.get("text"), lang), text, lang,
                                      f"{fwhere}.text.{lang}", lv, errors)
                rec["facts"].append(entry)

            # --- the historical curve ---------------------------------------
            key = lv.get("history")
            if content.get("history"):                 # hand-curated in the YAML
                series = content["history"]
                for field in ("unit", "source", "x", "y"):
                    if field not in series:
                        errors.append(f"{where}.history: '{field}' is required")
                if series.get("x") and len(series["x"]) != len(series.get("y", [])):
                    errors.append(f"{where}.history: x and y have different lengths")
                rec["history"] = {
                    "label": check_multilang(series.get("label", {}), languages,
                                             f"{where}.history.label", errors),
                    "unit": series.get("unit"), "source": series.get("source"),
                    "url": series.get("url"),
                    "x": series.get("x"), "y": series.get("y"), "curated": True,
                }
            elif content.get("historyAbsent"):
                if "historyNote" not in rec:
                    errors.append(f"{where}: historyAbsent needs a 'historyNote' explaining why")
                rec["historyAbsent"] = True
            elif key and key not in history_doc["series"]:
                errors.append(f"{where}: the notebook points this lever at history series "
                              f"'{key}', which does not exist. Either supply a curated "
                              f"'history' block or declare 'historyAbsent: true' with a "
                              f"'historyNote'.")
            elif not key:
                errors.append(f"{where}: no history series and no 'historyAbsent: true'")

            topic["levers"][lid] = rec

        # A topic may add interface strings of its own, so that a new topic can
        # be written without touching the shared ui.yaml. Collisions are an error
        # rather than a silent last-one-wins.
        for key, node in (doc.get("strings") or {}).items():
            if key in ui_strings:
                errors.append(f"{name}: string {key!r} is already defined "
                              f"(in ui.yaml or another topic); prefix it with the topic id")
                continue
            ui_strings[key] = check_multilang(node, languages, f"{name}.strings.{key}",
                                              errors)

        topics[topic_id] = topic

    if errors:
        print(f"{len(errors)} error(s):", file=sys.stderr)
        for err in errors:
            print("  -", err, file=sys.stderr)
        raise BuildError("content did not validate")

    for warn in warnings:
        print("  note:", warn)

    payload = {
        "generated": dt.date.today().isoformat(),
        "languages": languages,
        "defaultLanguage": default_lang,
        "ui": ui_strings,
        "topics": topics,
    }

    n_levers = sum(len(t["levers"]) for t in topics.values())
    n_facts = sum(len(l["facts"]) for t in topics.values() for l in t["levers"].values())
    print(f"ui strings   {len(ui_strings)} x {len(languages)} languages")
    print(f"topics       {len(topics)} ({', '.join(topics)})")
    print(f"levers       {n_levers} with {n_facts} facts")

    if check_only:
        print("\nvalidation only — nothing written")
        return 0

    body = json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("/* GENERATED by scripts/build_workshop_content.py from\n"
                 "   website/workshop/content/*.yaml — do not edit by hand. */\n")
        fh.write("window.NW_WS_CONTENT = " + body + ";\n")
    print(f"\nwrote {os.path.relpath(OUT, ROOT)} ({os.path.getsize(OUT) // 1024} kB)")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="validate without writing")
    args = ap.parse_args()
    try:
        return build(check_only=args.check)
    except BuildError as exc:
        print(f"\nBUILD FAILED: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
