#!/usr/bin/env bash
# =============================================================================
# négaWatt-BE workshop module — one-time MySQL provisioning (ROOT step)
#
# Creates the `negawatt_ws` database + user on labothap/negawatt.squoilin.eu,
# stores the credentials in two places, and applies the schema if the app has
# already been deployed.
#
#   sudo bash /home/sylvain/scripts/setup-negawatt-workshop-db.sh
#
# Idempotent: safe to re-run. The password is generated only once (on the first
# run) and reused afterwards, so re-running never breaks a live deployment.
#
# Written for the negaWatt-BE repo (scripts/setup-negawatt-workshop-db.sh).
# Follows the house convention documented in ~/llm/server-labothap.md.
# =============================================================================
set -euo pipefail

DB_NAME="negawatt_ws"
DB_USER="negawatt_ws"
DB_HOST="localhost"
SITE_USER="negawatt"
DOCROOT="/home/${SITE_USER}/public_html"
API_DIR="${DOCROOT}/api"
CONFIG="${API_DIR}/config.php"
ADMIN_CNF="/home/sylvain/.negawatt_ws.cnf"   # so later admin work needs no root
ADMIN_OWNER="sylvain"

log()  { printf '  %s\n' "$*"; }
step() { printf '\n== %s\n' "$*"; }
die()  { printf '\nERROR: %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "must run as root (sudo bash $0)"
command -v mysql >/dev/null || die "mysql client not found"
id "$SITE_USER" >/dev/null 2>&1 || die "system user '$SITE_USER' does not exist"

# --- 1. credentials -----------------------------------------------------------
step "Credentials"
if [[ -f "$ADMIN_CNF" ]]; then
    DB_PASS="$(awk -F= '/^password[[:space:]]*=/{gsub(/^[[:space:]]*|[[:space:]]*$/,"",$2); print $2; exit}' "$ADMIN_CNF")"
    [[ -n "$DB_PASS" ]] || die "$ADMIN_CNF exists but holds no password; delete it and re-run"
    log "reusing the existing password from $ADMIN_CNF"
    NEW_PASS=0
else
    DB_PASS="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)"
    log "generated a new 24-character password"
    NEW_PASS=1
fi

# --- 2. database + user -------------------------------------------------------
step "MySQL database and user"
mysql <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'${DB_HOST}' IDENTIFIED BY '${DB_PASS}';
ALTER USER '${DB_USER}'@'${DB_HOST}' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'${DB_HOST}';
FLUSH PRIVILEGES;
SQL
log "database '${DB_NAME}' and user '${DB_USER}'@'${DB_HOST}' are in place"

# --- 3. admin option file (root no longer needed after this) -------------------
step "Admin option file"
umask 077
cat > "$ADMIN_CNF" <<CNF
# négaWatt-BE workshop database — created by setup-negawatt-workshop-db.sh
# Usage: mysql --defaults-file=~/.negawatt_ws.cnf
[client]
host=127.0.0.1
user=${DB_USER}
password=${DB_PASS}
database=${DB_NAME}
CNF
chown "${ADMIN_OWNER}:${ADMIN_OWNER}" "$ADMIN_CNF"
chmod 600 "$ADMIN_CNF"
log "wrote $ADMIN_CNF (mode 600, owner ${ADMIN_OWNER})"

# --- 4. application config ----------------------------------------------------
step "Application config"
if [[ ! -d "$API_DIR" ]]; then
    mkdir -p "$API_DIR"
    chown "${SITE_USER}:${SITE_USER}" "$API_DIR"
    log "created $API_DIR (the app has not been deployed yet)"
fi

if [[ -f "$CONFIG" ]]; then
    log "$CONFIG already exists — left untouched"
else
    ADMIN_KEY="$(openssl rand -hex 24)"
    cat > "$CONFIG" <<PHP
<?php
/**
 * négaWatt-BE workshop — live configuration.
 * Generated by setup-negawatt-workshop-db.sh. NOT in git; never served (see /.htaccess).
 */
return [
    'db' => [
        'host'    => '127.0.0.1',
        'name'    => '${DB_NAME}',
        'user'    => '${DB_USER}',
        'pass'    => '${DB_PASS}',
        'charset' => 'utf8mb4',
    ],
    // Unlocks cross-session results (results.php?topic=...) on the reveal page.
    'admin_key' => '${ADMIN_KEY}',
    'base_url'  => 'https://negawatt.squoilin.eu',
];
PHP
    chown "${SITE_USER}:www-data" "$CONFIG"
    chmod 640 "$CONFIG"
    log "wrote $CONFIG (mode 640, ${SITE_USER}:www-data)"
    printf '\n  >>> Reveal-page admin key (needed to aggregate across sessions):\n'
    printf '      %s\n' "$ADMIN_KEY"
fi

# --- 5. schema ----------------------------------------------------------------
step "Schema"
SCHEMA="${API_DIR}/schema.sql"
if [[ -f "$SCHEMA" ]]; then
    mysql "$DB_NAME" < "$SCHEMA"
    log "applied $SCHEMA"
    mysql "$DB_NAME" -e "SHOW TABLES;" | sed 's/^/    /'
else
    log "no $SCHEMA yet — it will be applied after the first deployment with:"
    log "  mysql --defaults-file=~/.negawatt_ws.cnf < ${SCHEMA}"
    log "  (as user ${ADMIN_OWNER}; no root needed)"
fi

step "Done"
if [[ $NEW_PASS -eq 1 ]]; then
    log "A new DB password was generated and stored in $ADMIN_CNF and $CONFIG."
else
    log "Existing password reused; nothing else to do."
fi
log "The password is NOT printed here on purpose. Read it with:"
log "  sudo grep password $ADMIN_CNF"
